root: true
env:
  browser: true
  es2020: true
extends: 
  - 'airbnb'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - 'plugin:react-hooks/recommended'
ignorePatterns:
  - 'dist'
  - '.eslintrc.yml'
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    - version: '18.2'
plugins:
  - 'react-refresh'
rules: {
  react-refresh/only-export-components: [
    warn, { allowConstantExport: true }
  ],
  import/prefer-default-export: 0
}